// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial_Soliz_MJ.Data;

namespace Parcial_Soliz_MJ.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211013225905_AddModel")]
    partial class AddModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parcial_Soliz_MJ.Naipes.Naipe", b =>
                {
                    b.Property<string>("NaipeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Imagen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NaipeId");

                    b.ToTable("Naipe");
                });
#pragma warning restore 612, 618
        }
    }
}
